include ../Makefile.tests_common

USEMODULE += xtimer
USEMODULE += adxl345

FEATURES_REQUIRED += periph_cpuid
FEATURES_REQUIRED += periph_status
FEATURES_REQUIRED += periph_status_extended


include $(RIOTBASE)/Makefile.include
