APPLICATION = driver_fpc1020
BOARD = unwd-log
include ../Makefile.tests_common

FEATURES_REQUIRED += periph_spi
FEATURES_REQUIRED += periph_pm

USEMODULE += fpc1020
USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
