export CPU_MODEL = nrf52840xxaa
export CPU = nrf52

# set default port depending on operating system
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))
include $(RIOTMAKE)/tools/serial.inc.mk

# This board uses a DAP-Link programmer
export DEBUG_ADAPTER ?= dap

include $(RIOTMAKE)/tools/openocd.inc.mk
