/*
 * Copyright (C) 2016 Unwired Devices [info@unwds.com]
 *
 * This file is subject to the terms and conditions of the GNU Lesser
 * General Public License v2.1. See the file LICENSE in the top level
 * directory for more details.
 */

/**
 * @defgroup    
 * @ingroup     
 * @brief       
 * @{
 * @file		umdk-fdc1004.c
 * @brief       umdk-fdc1004 module implementation
 * @author      Oleg Artamonov <info@unwds.com>
 */

#ifdef __cplusplus
extern "C" {
#endif

/* define is autogenerated, do not change */
#undef _UMDK_MID_
#define _UMDK_MID_ UNWDS_FDC1004_MODULE_ID

/* define is autogenerated, do not change */
#undef _UMDK_NAME_
#define _UMDK_NAME_ "fdc1004"

#include <stdlib.h>
#include <stdbool.h>
#include <string.h>

#include "periph/gpio.h"
#include "periph/i2c.h"

#include "board.h"

#include "fdc1004.h"

#include "unwds-common.h"
#include "umdk-fdc1004.h"

#include "thread.h"
#include "rtctimers-millis.h"

static fdc1004_t dev;

static uwnds_cb_t *callback;

static kernel_pid_t timer_pid;

static msg_t timer_msg = {};
static rtctimers_millis_t timer;

static bool is_polled = false;

static struct {
	uint8_t publish_period_min;
	uint8_t i2c_dev;
} fdc1004_config;

static bool init_sensor(void) {
	dev.i2c = UMDK_FDC1004_I2C;

	printf("[umdk-" _UMDK_NAME_ "] Initializing fdc1004 on I2C #%d\n", dev.i2c);

	return fdc1004_init(&dev) == 0;
}

static void prepare_result(module_data_t *buf) {
    
	uint32_t capacitance[4];
    
    for (int i = 0; i < 4; i++) {
        capacitance[i] = fdc1004_get_capacitance(&dev, i+1);
        printf("[umdk-" _UMDK_NAME_ "] Channel %d: %lu\n", i+1, capacitance[i]);
    }

    if (buf) {
        buf->length = 1 + sizeof(capacitance); /* Additional byte for module ID */
        buf->data[0] = _UMDK_MID_;
        /* Copy measurements into response */
        memcpy(buf->data + 1, (uint8_t *) &capacitance, sizeof(capacitance));
    }
}

static void *timer_thread(void *arg) {
    (void) arg;
    msg_t msg;
    msg_t msg_queue[4];
    msg_init_queue(msg_queue, 4);
    
    puts("[umdk-" _UMDK_NAME_ "] Periodic publisher thread started");

    while (1) {
        msg_receive(&msg);

        module_data_t data = {};
        data.as_ack = is_polled;
        is_polled = false;

        prepare_result(&data);

        /* Notify the application */
        callback(&data);

        /* Restart after delay */
        rtctimers_millis_set_msg(&timer, 60000 * fdc1004_config.publish_period_min, &timer_msg, timer_pid);
    }

    return NULL;
}

static void reset_config(void) {
	fdc1004_config.publish_period_min = UMDK_FDC1004_PUBLISH_PERIOD_MIN;
	fdc1004_config.i2c_dev = UMDK_FDC1004_I2C;
}

static void init_config(void) {
	reset_config();

	if (!unwds_read_nvram_config(_UMDK_MID_, (uint8_t *) &fdc1004_config, sizeof(fdc1004_config)))
		reset_config();

	if (fdc1004_config.i2c_dev >= I2C_NUMOF) {
		reset_config();
		return;
	}
}

static inline void save_config(void) {
	unwds_write_nvram_config(_UMDK_MID_, (uint8_t *) &fdc1004_config, sizeof(fdc1004_config));
}

static void set_period (int period) {
    rtctimers_millis_remove(&timer);

    fdc1004_config.publish_period_min = period;
	save_config();

	/* Don't restart timer if new period is zero */
	if (fdc1004_config.publish_period_min) {
        rtctimers_millis_set_msg(&timer, 60000 * fdc1004_config.publish_period_min, &timer_msg, timer_pid);
		printf("[umdk-" _UMDK_NAME_ "] Period set to %d minute (s)\n", fdc1004_config.publish_period_min);
    } else {
        puts("[umdk-" _UMDK_NAME_ "] Timer stopped");
    }
}

int umdk_fdc1004_shell_cmd(int argc, char **argv) {
    if (argc == 1) {
        puts (_UMDK_NAME_ " get - get results now");
        puts (_UMDK_NAME_ " send - get and send results now");
        puts (_UMDK_NAME_ " period <N> - set period to N minutes");
        puts (_UMDK_NAME_ " reset - reset settings to default");
        return 0;
    }
    
    char *cmd = argv[1];
	
    if (strcmp(cmd, "get") == 0) {
        prepare_result(NULL);
    }
    
    if (strcmp(cmd, "send") == 0) {
		/* Send signal to publisher thread */
		msg_send(&timer_msg, timer_pid);
    }
    
    if (strcmp(cmd, "period") == 0) {
        char *val = argv[2];
        set_period(atoi(val));
    }
    
    if (strcmp(cmd, "reset") == 0) {
        reset_config();
        save_config();
    }
    
    return 1;
}

static void btn_connect(void* arg) {
    (void) arg;
    is_polled = false;
    msg_send(&timer_msg, timer_pid);
}

void umdk_fdc1004_init(uint32_t *non_gpio_pin_map, uwnds_cb_t *event_callback) {
	(void) non_gpio_pin_map;

	callback = event_callback;

	init_config();
	printf("[umdk-" _UMDK_NAME_ "] Publish period: %d min\n", fdc1004_config.publish_period_min);

	if (!init_sensor()) {
		puts("[umdk-" _UMDK_NAME_ "] Unable to init sensor!");
        return;
	}

	/* Create handler thread */
	char *stack = (char *) allocate_stack(UMDK_FDC1004_STACK_SIZE);
	if (!stack) {
		puts("[umdk-" _UMDK_NAME_ "] unable to allocate memory. Are too many modules enabled?");
		return;
	}
    
    unwds_add_shell_command( _UMDK_NAME_, "type '" _UMDK_NAME_ "' for commands list", umdk_fdc1004_shell_cmd);

#ifdef UNWD_CONNECT_BTN
    if (UNWD_USE_CONNECT_BTN) {
        gpio_init_int(UNWD_CONNECT_BTN, GPIO_IN_PU, GPIO_FALLING, btn_connect, NULL);
    }
#endif
    
	timer_pid = thread_create(stack, UMDK_FDC1004_STACK_SIZE, THREAD_PRIORITY_MAIN - 1, THREAD_CREATE_STACKTEST, timer_thread, NULL, "fdc1004 thread");

    /* Start publishing timer */
	rtctimers_millis_set_msg(&timer, 60000 * fdc1004_config.publish_period_min, &timer_msg, timer_pid);
}

static void reply_fail(module_data_t *reply) {
	reply->length = 2;
	reply->data[0] = _UMDK_MID_;
	reply->data[1] = 255;
}

static void reply_ok(module_data_t *reply) {
	reply->length = 2;
	reply->data[0] = _UMDK_MID_;
	reply->data[1] = 0;
}

bool umdk_fdc1004_cmd(module_data_t *cmd, module_data_t *reply) {
	if (cmd->length < 1) {
		reply_fail(reply);
		return true;
	}

	umdk_fdc1004_cmd_t c = cmd->data[0];
	switch (c) {
	case UMDK_FDC1004_CMD_SET_PERIOD: {
		if (cmd->length != 2) {
			reply_fail(reply);
			break;
		}

		uint8_t period = cmd->data[1];
		set_period(period);

		reply_ok(reply);
		break;
	}

	case UMDK_FDC1004_CMD_POLL:
		is_polled = true;

		/* Send signal to publisher thread */
		msg_send(&timer_msg, timer_pid);

		return false; /* Don't reply */

	case UMDK_FDC1004_CMD_SET_I2C: {
		i2c_t i2c = (i2c_t) cmd->data[1];
		dev.i2c = i2c;

		fdc1004_config.i2c_dev = i2c;

		init_sensor();

		reply_ok(reply);
		break;
	}

	default:
		reply_fail(reply);
		break;
	}

	return true;
}

#ifdef __cplusplus
}
#endif
