# name of your application
APPLICATION = atmodem-public

# application-specific modules
USEMODULE += sim5300
USEMODULE += at
USEMODULE += base64

USEPKG += paho-embed-mqtt3c

include ../unwds-common/Makefile.include
