# The ADC does not depend on any board configuration, so always available
FEATURES_PROVIDED += periph_adc

FEATURES_PROVIDED += periph_pwm
FEATURES_PROVIDED += periph_nfc

-include $(RIOTCPU)/nrf5x_common/Makefile.features
