/*
 * Copyright (C) 2016-2018 Unwired Devices LLC <info@unwds.com>

 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software
 * is furnished to do so, subject to the following conditions:

 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
 * PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
 * FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/**
 * @defgroup
 * @ingroup
 * @brief
 * @{
 * @file		umdk-gassensor.c
 * @brief       LMP91000-based gas sensor module
 * @author      
 */

#ifdef __cplusplus
extern "C" {
#endif

/* define is autogenerated, do not change */
#undef _UMDK_MID_
#define _UMDK_MID_ UNWDS_GASSENSOR_MODULE_ID

/* define is autogenerated, do not change */
#undef _UMDK_NAME_
#define _UMDK_NAME_ "gassensor"

#include <stdlib.h>
#include <stdbool.h>
#include <string.h>

#include "periph/gpio.h"
#include "periph/adc.h"
#include "board.h"

#include "umdk-ids.h"
#include "unwds-common.h"

#include "umdk-gassensor.h"

#include "thread.h"
#include "rtctimers-millis.h"

static uwnds_cb_t *callback;

static kernel_pid_t timer_pid;

static msg_t timer_msg = {};
static rtctimers_millis_t timer;

static bool is_polled = false;

static struct {
	uint8_t                     publish_period_sec;
    umdk_gassensor_sensor_t     sensor_type;
    uint32_t                    sensor_code;
} gassensor_config;

static void reset_config(void) {
	gassensor_config.publish_period_sec = UMDK_GASSENSOR_PUBLISH_PERIOD_MIN;
    gassensor_config.sensor_type = UMDK_GASSENSOR_UNKNOWN;
    gassensor_config.sensor_code = 0;
}

static void init_config(void) {
	reset_config();

	if (!unwds_read_nvram_config(_UMDK_MID_, (uint8_t *) &gassensor_config, sizeof(gassensor_config))) {
        reset_config();
    }
        
	printf("[umdk-" _UMDK_NAME_ "] Publish period: %d min\n", gassensor_config.publish_period_sec);
}

static inline void save_config(void) {
	unwds_write_nvram_config(_UMDK_MID_, (uint8_t *) &gassensor_config, sizeof(gassensor_config));
}

static void init_gassensor(void)
{
    /* code here */
    adc_init(ADC_LINE(3));
}

static void prepare_result(module_data_t *buf)
{
    uint16_t ppm;
    /* obtain data */

    if (buf) {
        buf->data[0] = _UMDK_MID_;
        buf->data[1] = UMDK_GASSENSOR_DATA;
        memcpy(buf->data + 2, (void *)&ppm, sizeof(ppm));
        buf->length = sizeof(ppm) + 2;
    }
}

static void *timer_thread(void *arg)
{
    (void)arg;
    
    msg_t msg;
    msg_t msg_queue[4];
    msg_init_queue(msg_queue, 4);

    puts("[umdk-" _UMDK_NAME_ "] Periodic publisher thread started");

    while (1) {
        msg_receive(&msg);

        module_data_t data = {};
        data.as_ack = is_polled;
        is_polled = false;

        prepare_result(&data);

        /* Notify the application */
        callback(&data);

        /* Restart after delay */
        rtctimers_millis_set_msg(&timer, 1000 * gassensor_config.publish_period_sec, &timer_msg, timer_pid);
    }

    return NULL;
}

static void set_period (int period) {
    gassensor_config.publish_period_sec = period;
    save_config();

    /* Don't restart timer if new period is zero */
    if (gassensor_config.publish_period_sec) {
        rtctimers_millis_set_msg(&timer, 1000 * gassensor_config.publish_period_sec, &timer_msg, timer_pid);
        printf("[umdk-" _UMDK_NAME_ "] Period set to %d minutes\n", gassensor_config.publish_period_sec);
    } else {
        puts("[umdk-" _UMDK_NAME_ "] Timer stopped");
    }
}

int umdk_gassensor_shell_cmd(int argc, char **argv) {
    if (argc == 1) {
        puts (_UMDK_NAME_ " get - get results now");
        puts (_UMDK_NAME_ " send - get and send results now");
        puts (_UMDK_NAME_ " period <N> - set period to N minutes");
        puts (_UMDK_NAME_ " sensor <type> - set sensor type (H2S, CO, O3, NO2, SO2)");
        puts (_UMDK_NAME_ " code <value> - set sensor sensitivity code pA/ppm");
        puts (_UMDK_NAME_ " reset - reset settings to default");
        return 0;
    }
    
    char *cmd = argv[1];
	
    if (strcmp(cmd, "get") == 0) {
        prepare_result(NULL);
    }
    
    if (strcmp(cmd, "send") == 0) {
		/* Send signal to publisher thread */
		msg_send(&timer_msg, timer_pid);
    }
    
    if (strcmp(cmd, "period") == 0) {
        char *val = argv[2];
        set_period(atoi(val));
    }
    
    if (strcmp(cmd, "reset") == 0) {
        reset_config();
        save_config();
    }
    
    if (strcmp(cmd, "sensor") == 0) {
        /* code here */
        char *val = argv[2];
        if (strcmp(val, "H2S") == 0) {
            gassensor_config.sensor_type = UMDK_GASSENSOR_H2S;
        } else if (strcmp(val, "CO") == 0) {
            gassensor_config.sensor_type = UMDK_GASSENSOR_CO;
        } else if (strcmp(val, "O3") == 0) {
            gassensor_config.sensor_type = UMDK_GASSENSOR_O3;
        } else if (strcmp(val, "NO2") == 0) {
            gassensor_config.sensor_type = UMDK_GASSENSOR_NO2;
        } else if (strcmp(val, "SO2") == 0) {
            gassensor_config.sensor_type = UMDK_GASSENSOR_SO2;
        } else {
            gassensor_config.sensor_type = UMDK_GASSENSOR_UNKNOWN;
        }
        if (gassensor_config.sensor_type != UMDK_GASSENSOR_UNKNOWN) {
            save_config();
        } else {
            puts("Set sensor type is unknown");
        }
    }

    if (strcmp(cmd, "code") == 0) {
        /* insert code here */
        char *val = argv[2];
        gassensor_config.sensor_code = atoi(val);
        save_config();
    }
    
    return 1;
}

void umdk_gassensor_init(uwnds_cb_t *event_callback)
{

    callback = event_callback;
    init_config();

    init_gassensor();

    /* Create handler thread */
    char *stack = (char *) allocate_stack(UMDK_GASSENSOR_STACK_SIZE);
    if (!stack) {
    	return;
    }

    unwds_add_shell_command( _UMDK_NAME_, "type '" _UMDK_NAME_ "' for commands list", umdk_gassensor_shell_cmd);

    timer_pid = thread_create(stack, UMDK_GASSENSOR_STACK_SIZE, THREAD_PRIORITY_MAIN - 1, THREAD_CREATE_STACKTEST, timer_thread, NULL, "ADC thread");

    /* Start publishing timer */
    rtctimers_millis_set_msg(&timer, 1000 * gassensor_config.publish_period_sec, &timer_msg, timer_pid);
}

static void reply_ok(module_data_t *reply)
{
    reply->length = 4;
    reply->data[0] = _UMDK_MID_;
    reply->data[1] = UMDK_GASSENSOR_CMD_COMMAND;
    reply->data[2] = gassensor_config.publish_period_sec;
}

static void reply_fail(module_data_t *reply)
{
    reply->length = 2;
    reply->data[0] = _UMDK_MID_;
    reply->data[1] = UMDK_GASSENSOR_FAIL;
}

bool umdk_gassensor_cmd(module_data_t *cmd, module_data_t *reply)
{
    if (cmd->length < 1) {
    	reply_fail(reply);
        return true;
    }

    umdk_gassensor_cmd_t c = cmd->data[0];
    switch (c) {
        case UMDK_GASSENSOR_CMD_COMMAND: {
            /* leave it empty for a while */

            reply_ok(reply);
            break;
        }

        case UMDK_GASSENSOR_CMD_POLL:
        	is_polled = true;

            /* Send signal to publisher thread */
            msg_send(&timer_msg, timer_pid);

            return false; /* Don't reply */

            break;
            
        default:
            reply_fail(reply);
            break;
    }

    return true;
}

#ifdef __cplusplus
}
#endif
