APPLICATION = lpm_test
include ../Makefile.tests_common

#DISABLE_MODULE += auto_init

USEMODULE += od
USEMODULE += ps
USEMODULE += xtimer

CFLAGS += -DDEVELHELP

include $(RIOTBASE)/Makefile.include
