/*
 * Copyright (C) 2016 cr0s
 *
 * This file is subject to the terms and conditions of the GNU Lesser
 * General Public License v2.1. See the file LICENSE in the top level
 * directory for more details.
 */

/**
 * @defgroup
 * @ingroup
 * @brief
 * @{
 * @file
 * @brief
 * @author      cr0s
 */

#ifdef __cplusplus
extern "C" {
#endif

/* define is autogenerated, do not change */
#undef _UMDK_MID_
#define _UMDK_MID_ UNWDS_CONFIG_MODULE_ID

/* define is autogenerated, do not change */
#undef _UMDK_NAME_
#define _UMDK_NAME_ "config"

#include <stdlib.h>
#include <stdbool.h>
#include <string.h>

#include "board.h"
#include "unwds-common.h"
#include "ls-settings.h"

#include "umdk-config.h"

#define ENABLE_DEBUG (0)
#include "debug.h"

void umdk_config_init(uint32_t *non_gpio_pin_map, uwnds_cb_t *event_callback)
{
    (void) non_gpio_pin_map;
    (void) event_callback;
}

static inline void do_reply(module_data_t *reply, umdk_config_reply_t reply_code)
{
    reply->length = 2;
    reply->data[0] = _UMDK_MID_;
    reply->data[1] = reply_code;
}

static bool config_cmd(module_data_t *cmd, module_data_t *reply, bool with_reply)
{
    uint8_t command = cmd->data[0];

    switch (command) {
        case UMDK_CONFIG_MODULES: {
            uint8_t id = cmd->data[1];
            uint8_t onoff = cmd->data[2];
            if (!unwds_is_module_exists(id)) {
                do_reply(reply, UMDK_CONFIG_REPLY_ERR);
                return false;
            }
            
            unwds_set_module(id, onoff);
            unwds_config_save();
            
            char status[10];
            if (onoff) {
                strcpy(status, "enabled");
            } else {
                strcpy(status, "disabled");
            }
            printf("[umdk-" _UMDK_NAME_ "] Module %d %s, configuration saved\n", (int) id, status);
            
            do_reply(reply, UMDK_CONFIG_REPLY_OK);
            break;
        }
        default:
            do_reply(reply, UMDK_CONFIG_REPLY_ERR);
            break;
    }

    return true;
}

bool umdk_config_cmd(module_data_t *cmd, module_data_t *reply)
{
    return config_cmd(cmd, reply, true);
}

#ifdef __cplusplus
}
#endif
