APPLICATION = driver_l1_nvram_test
include ../Makefile.tests_common

#DISABLE_MODULE += auto_init

USEMODULE += od
USEMODULE += ps
USEMODULE += xtimer
USEMODULE += l1-nvram-eeprom

CFLAGS += -DDEVELHELP

include $(RIOTBASE)/Makefile.include
