export CPU_ARCH = cortex-m3
export CPU_FAM  = stm32l1

CFLAGS += -DPROVIDES_PM_SET_LOWEST_CORTEXM

FEATURES_REQUIRED += periph_rtc

include $(RIOTCPU)/stm32_common/Makefile.include
include $(RIOTMAKE)/arch/cortexm.inc.mk

ifneq (,$(findstring xtimer,$(USEMODULE)))
    CFLAGS += -DXTIMER_PRESENT
endif