export CPU_ARCH = cortex-m0
export CPU_FAM  = stm32f0

CFLAGS += -DPROVIDES_PM_SET_LOWEST_CORTEXM

FEATURES_REQUIRED += periph_rtc
FEATURES_REQUIRED += periph_pm

include $(RIOTCPU)/stm32_common/Makefile.include
include $(RIOTMAKE)/arch/cortexm.inc.mk

ifneq (,$(findstring xtimer,$(USEMODULE)))
    CFLAGS += -DXTIMER_PRESENT
endif