/*
 * Copyright (C) 2018 Unwired Devices LLC <info@unwds.com>

 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software
 * is furnished to do so, subject to the following conditions:

 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
 * PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
 * FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/**
 * @defgroup
 * @ingroup
 * @brief
 * @{
 * @file		umdk-soil.c
 * @brief       umdk-soil module implementation
 * @author      Oleg Artamonov
 */

#ifdef __cplusplus
extern "C" {
#endif

/* define is autogenerated, do not change */
#undef _UMDK_MID_
#define _UMDK_MID_ UNWDS_SOIL_MODULE_ID

/* define is autogenerated, do not change */
#undef _UMDK_NAME_
#define _UMDK_NAME_ "soil"

#include <stdlib.h>
#include <stdbool.h>
#include <string.h>

#include "board.h"

#include "umdk-ids.h"
#include "unwds-common.h"
#include "include/umdk-soil.h"

#include "thread.h"
#include "xtimer.h"
#include "rtctimers-millis.h"

#define ENABLE_DEBUG (0)
#include "debug.h"

static uwnds_cb_t *callback;

typedef struct {
    uint8_t publish_period_sec;
} umdk_soil_config_t;

static umdk_soil_config_t umdk_soil_config = { .publish_period_sec = 5};

static bool is_polled = false;
static rtctimers_millis_t timer;
static msg_t timer_msg = {};
static kernel_pid_t timer_pid;

static void prepare_result(module_data_t *data) {
	
    if (data) {
        data->data[0] = _UMDK_MID_;
        memcpy(data->data + 1, (uint8_t *) res, sizeof(res));
        data->length = sizeof(res) + 1;
    }
}

static void *timer_thread(void *arg) {
    (void)arg;

    msg_t msg;
    msg_t msg_queue[4];
    msg_init_queue(msg_queue, 4);

    puts("[umdk-" _UMDK_NAME_ "] Periodic publisher thread started");

    while (1) {
        msg_receive(&msg);

        module_data_t data = {};
        data.as_ack = is_polled;
        is_polled = false;

        prepare_result(&data);

        /* Notify the application */
        callback(&data);

        /* Restart after delay */
        rtctimers_millis_set_msg(&timer, 60000 * soil_config.publish_period_min, &timer_msg, timer_pid);
    }
    
    return NULL;
}

static void reset_config(void) {
    umdk_soil_config.publish_period_sec = 60;
}

static void init_config(void) {
	reset_config();

	if (!unwds_read_nvram_config(_UMDK_MID_, (uint8_t *) &umdk_soil_config, sizeof(umdk_soil_config)))
		reset_config();
}

static inline void save_config(void) {
	unwds_write_nvram_config(_UMDK_MID_, (uint8_t *) &umdk_soil_config, sizeof(umdk_soil_config));
}

int umdk_soil_shell_cmd(int argc, char **argv) {
    if (argc == 1) {
        puts ("soil send - obtain data from sensor");
        puts ("soil send - obtain and send data");
        puts ("soil period <period> - set publishing period");
        puts ("soil reset - reset settings to default");
        return 0;
    }
    
    char *cmd = argv[1];
    
    if (strcmp(cmd, "get") == 0) {
        prepare_result(NULL);
    }
    
    if (strcmp(cmd, "send") == 0) {
        /* Send signal to publisher thread */
		msg_send(&timer_msg, timer_pid);
    }
    
    if (strcmp(cmd, "period") == 0) {
        char *val = argv[2];
        umdk_soil_config.publish_period_sec = atoi(val);
        save_config();
    }
    
    if (strcmp(cmd, "reset") == 0) {
        reset_config();
        save_config();
    }
    
    return 1;
}

void umdk_soil_init(uwnds_cb_t *event_callback)
{
    callback = event_callback;

    init_config();
    
    soil.reader_stack = (uint8_t *) allocate_stack(UMDK_SOIL_READER_STACK_SIZE);
    if (!soil.reader_stack) {
        return;
    }

    char *timer_stack = (char *) allocate_stack(UMDK_SOIL_STACK_SIZE);
    if (!timer_stack) {
        return;
    }
    timer_pid = thread_create(timer_stack, UMDK_SOIL_STACK_SIZE, THREAD_PRIORITY_MAIN - 1, THREAD_CREATE_STACKTEST, timer_thread, NULL, "umdk-soil timer thread");
    /* Start publishing timer */
    rtctimers_millis_set_msg(&timer, 1000*umdk_soil_config.publish_period_sec, &timer_msg, timer_pid);

    unwds_add_shell_command("soil", "type 'soil' for commands list", umdk_soil_shell_cmd);

}

static void reply_fail(module_data_t *reply) {
	reply->length = 2;
	reply->data[0] = _UMDK_MID_;
	reply->data[1] = UMDK_SOIL_ERR;
}

static void reply_ok(module_data_t *reply) {
	reply->length = 2;
	reply->data[0] = _UMDK_MID_;
	reply->data[1] = UMDK_SOIL_REPLY_OK;
}

bool umdk_soil_cmd(module_data_t *data, module_data_t *reply)
{
    if (data->length < 1) {
        do_reply(reply, UMDK_SOIL_REPLY_ERR_FMT);
        return true;
    }

    umdk_soil_prefix_t prefix = data->data[0];
    switch (prefix) {
        case UMDK_SOIL_ASK:
            is_polled = true;
            msg_send(&timer_msg, timer_pid);
            break;
            
        case UMDK_SOIL_SET_PERIOD:
            if (data->length != 2) {
                do_reply(reply, UMDK_SOIL_REPLY_ERR_FMT);
                break;
            }
            umdk_soil_config.publish_period_sec = 60*(data->data[1]);
            do_reply(reply, UMDK_SOIL_REPLY_OK);
            break;

        default:
        	do_reply(reply, UMDK_SOIL_REPLY_ERR_FMT);
        	break;
    }

    return true;
}

bool umdk_soil_cmd(module_data_t *cmd, module_data_t *reply) {
	if (cmd->length < 1) {
		reply_fail(reply);
		return true;
	}

	umdk_soil_cmd_t c = cmd->data[0];
	switch (c) {
	case UMDK_SOIL_CMD_SET_PERIOD: {
		if (cmd->length != 2) {
			reply_fail(reply);
			break;
		}

		uint8_t period = cmd->data[1];
		set_period(period);

		reply_ok(reply);
		break;
	}

	case UMDK_SOIL_CMD_POLL:
		is_polled = true;

		/* Send signal to publisher thread */
		msg_send(&timer_msg, timer_pid);

		return false; /* Don't reply now */

		break;

	case UMDK_SOIL_CMD_SET_GPIOS: {
		uint8_t *gpios = &cmd->data[1];
		int num_gpios = cmd->length - 1;

		if (!num_gpios) {
			reply_fail(reply);
			break;
		}

		int i;
		for (i = 0; i < num_gpios; i++) {
			if (gpios[i]) {
				gpio_t gpio = unwds_gpio_pin(gpios[i]);
				en_pins[i] = gpio;
			} else
				en_pins[i] = 0;	/* Disable this pin */
		}

		/* Re-initialize sensors */
		init_sensors();

		reply_ok(reply);
		break;
	}

	default:
		reply_ok(reply);
		break;
	}

	return true;
}

#ifdef __cplusplus
}
#endif
