include ../Makefile.tests_common

USEMODULE += fdc1004


USEMODULE += dsp_dia
USEMODULE += ps
USEMODULE += xtimer


FEATURES_REQUIRED += periph_rtc
FEATURES_REQUIRED += periph_cpuid
FEATURES_REQUIRED += periph_status
FEATURES_REQUIRED += periph_status_extended



include $(RIOTBASE)/Makefile.include
