# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_adc
FEATURES_PROVIDED += periph_cpuid
FEATURES_PROVIDED += periph_gpio
FEATURES_PROVIDED += periph_pm
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart
FEATURES_PROVIDED += periph_flashpage
FEATURES_PROVIDED += periph_rtc

# The board MPU family (used for grouping by the CI system)
FEATURES_MCU_GROUP = cortex_m0_1
