include ../Makefile.tests_common

USEPKG += paho-embed-mqtt3c

FEATURES_REQUIRED += periph_cpuid
FEATURES_REQUIRED += periph_status
FEATURES_REQUIRED += periph_status_extended
FEATURES_REQUIRED += periph_rtc

include $(RIOTBASE)/Makefile.include