# name of your application
APPLICATION = lorawan

# application-specific modules
USEPKG += semtech-loramac

CFLAGS += -DUNWDS_MAC_LORAWAN

# to be removed later
# CFLAGS += -DLORAWAN_DONT_USE_FPORT

include ../unwds-common/Makefile.include
