APPLICATION = rtctimers_millis_test
BOARD = unwd-range-l1-r3

include ../Makefile.tests_common

#DISABLE_MODULE += auto_init

USEMODULE += od
USEMODULE += ps
USEMODULE += rtctimers
USEMODULE += rtctimers-millis
USEMODULE += xtimer

CFLAGS += -DDEVELHELP

include $(RIOTBASE)/Makefile.include
