include ../Makefile.tests_common

USEMODULE += fdc2212


USEMODULE += dsp_dia
USEMODULE += ps
USEMODULE += lptimer

FEATURES_PROVIDED += lptimer

FEATURES_REQUIRED += periph_cpuid
FEATURES_REQUIRED += periph_status
FEATURES_REQUIRED += periph_status_extended



include $(RIOTBASE)/Makefile.include