# name of your application
APPLICATION = loralan-public

# application-specific modules
USEMODULE += loralan-device
USEMODULE += loralan-mac

DIRS += $(RIOTBASE)/apps/unwds-common/loralan-mac/
DIRS += $(RIOTBASE)/apps/unwds-common/loralan-device/

INCLUDES += -I$(RIOTBASE)/apps/unwds-common/loralan-device/include/

include ../unwds-common/Makefile.include
